version: "3.9"

services:

  otel-collector:
    container_name: otel-collector
    image: ${COLLECTOR_CONTRIB_IMAGE}
    volumes:
      - ${OTEL_COLLECTOR_CONFIG_EXTRAS}:/etc/otelcol-config.yml
      - ${HOST_FILESYSTEM}:/hostfs:ro
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
    command: ["--config=/etc/otelcol-config.yml"]
    ports:
      - "${OTEL_COLLECTOR_PORT_GRPC}"
      - "${OTEL_COLLECTOR_PORT_HTTP}"
    restart: always
    user: 0:0
    environment:
      - ENVOY_PORT
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - HOST_FILESYSTEM
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
      - OTEL_COLLECTOR_PORT_HTTP
      - GOMEMLIMIT=160MiB
      - VICTORIALOGS_HOST
      - VICTORIALOGS_PORT

  tracegen:
    container_name: tracegen
    build:
      context: tracegen
      dockerfile: Dockerfile
    command:
    - "-service=tracegen"
    - "-rate=500"
    - "-workers=200"
    - "-duration=5m" 
    - "-otlp-endpoint=otel-collector:4317"
    - "-otlp-insecure"
     
    depends_on:
      - victorialogs

  victorialogs:
    image: victoriametrics/victoria-logs:heads-feature-otlp-trace-ingestion-0-g8f42fd45b
    container_name: victorialogs
    ports:
      - "${VICTORIALOGS_PORT}:${VICTORIALOGS_PORT}"
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: 2