version: '3.9'

volumes:
  prometheus:

services:
  
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus-config.yaml
      - prometheus:/prometheus
    deploy:
      resources:
        limits:
          memory: 300M
    

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_INSTALL_PLUGINS=grafana-opensearch-datasource, grafana-clickhouse-datasource"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    restart: always

  docker-exporter:
    image: ghcr.io/davidborzek/docker-exporter:latest
    container_name: docker-exporter
    user: 0:0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped



