# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  docker_stats:
    endpoint: unix:///var/run/docker.sock
  # Host metrics
  hostmetrics:
    root_path: /hostfs
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      load:
      filesystem:
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/k3s/containerd/*
            - /var/lib/docker/*
            - /var/lib/kubelet/*
            - /snap/*
            - /hostfs/oldroot
          match_type: regexp
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
      paging:
      processes:
      process:
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true




exporters:
  debug:
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true
  clickhouse:
    endpoint: "tcp://clickhouse:9000?dial_timeout=10s&compress=lz4"
    # endpoint: "http://clickhouse:8123" # Connect to the ClickHouse service within Docker network
    traces_table_name: "otel_traces"
    username: "default"
    password: "hello2Jaeger"

processors:
  batch:
   timeout: 2s
   send_batch_size: 100000
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25


service:
  pipelines:
    metrics:
      receivers: [hostmetrics, docker_stats]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/prometheus, debug]
    traces:
      receivers: [otlp] 
      processors: [batch]
      exporters: [clickhouse]