# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: victorialogs
    uid: vl-traces
    type: jaeger
    url: http://victorialogs:9428/select/jaeger/
    editable: true
    isDefault: false
